#!/bin/bash -e
# Regen FOG MySQL user random password
# currently just a copy of concrete5 gen-secrets...

. /etc/default/inithooks

PASSWORD=$(mcookie)
CONF_PATH=/var/www/fog/whever...

mv $CONF_PATH/site.php $CONF_PATH/oldsite.php
grep -v "^\define('DB_PASSWORD" $CONF_PATH/oldsite.php > $CONF_PATH/site.php
echo "define('DB_PASSWORD', '"$PASSWORD"');" >> $CONF_PATH/site.php

$INITHOOKS_PATH/bin/mysqlconf.py --user=fog-usr --pass="$PASSWORD"