#!/bin/bash -e
# FOG firstboot config file

# set FOG admin password, ip and other options

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/fog.py --pass="$APP_PASS" --ip="$APP_IP" --use-dhcp="$APP_USE_DHCP" --interface="$APP_IF" --route="$APP_ROUTE" --dns="$APP_DNS"
