#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

HOSTNAME=fog-server

# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

cd /opt
wget http://sourceforge.net/projects/freeghost/files/FOG/fog_0.32/fog_0.32.tar.gz -O fog-setup.tar.gz
tar xvzf fog-setup.tar.gz

install php5-gd php5-cli php5-curl mysql-client dhcp3-server tftpd-hpa tftp-hpa nfs-kernel-server vsftpd net-tools xinetd sysv-rc-conf build-essential cpp gcc g++ m4 htmldoc libcrypt-passwdmd5-perl lftp openssh-server php-gettext clamav-freshclam

#config funtions
configureUsers;
			configureMySql;
			backupReports;
			configureHttpd;
			restoreReports;
			setupFreshClam;
			configureStorage;
			configureNFS;
			configureDHCP;
			configureTFTPandPXE;
			configureFTP;
			configureSudo;
			configureSnapins;
			configureUDPCast;          
			installInitScript;
			installFOGServices;
			configureFOGService;
			installUtils;
			sendInstallationNotice;
			writeUpdateFile;

